server:
  port: 8000
spring:
  application:
    name: RentACar
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar?serverTimeZone=ADT
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
spring-doc:
  api-docs:
    path: /api-docs
    pathsToMatch: /api/**
    swagger-ui:
      use-root-path: true

